// PulsarIQ — Premium Landing Page with Embedded Login
// Run: node phase5c.js

const fs   = require('fs');
const path = require('path');
const root = process.cwd();

function write(filePath, content) {
  const full = path.join(root, filePath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content, 'utf8');
  console.log('  \u2713', filePath);
}

console.log('\n  PulsarIQ \u2014 Phase 5C: Cinematic Landing\n');

const lines = [];
lines.push("'use client';");
lines.push("import { useEffect, useRef, useState } from 'react';");
lines.push("import { useRouter } from 'next/navigation';");
lines.push("import { createClient } from '@/lib/supabase/client';");
lines.push("import { Zap, ArrowRight, ChevronDown } from 'lucide-react';");
lines.push("");
lines.push("// Lorenz attractor");
lines.push("const S=10,R=28,B=8/3,DT=0.005,TRAIL=1400;");
lines.push("const SEEDS=[{x:0.1,y:0,z:0},{x:0.12,y:0.02,z:0.1},{x:-0.1,y:0.01,z:0},{x:0.05,y:-0.05,z:0.2}];");
lines.push("const COLORS=[[99,102,241],[34,211,238],[168,85,247],[99,102,241]];");
lines.push("");
lines.push("export default function LandingPage() {");
lines.push("  const canvasRef = useRef<HTMLCanvasElement>(null);");
lines.push("  const dataRef   = useRef<{frame:number;pts:{x:number;y:number;z:number;trail:{px:number;py:number}[]}[]}>({");
lines.push("    frame:0, pts: SEEDS.map(s => ({...s, trail:[]}))");
lines.push("  });");
lines.push("  const animRef  = useRef<number>(0);");
lines.push("  const [email, setEmail]       = useState('');");
lines.push("  const [password, setPassword] = useState('');");
lines.push("  const [error, setError]       = useState('');");
lines.push("  const [loading, setLoading]   = useState(false);");
lines.push("  const [mode, setMode]         = useState<'login'|'signup'>('login');");
lines.push("  const router   = useRouter();");
lines.push("  const supabase = createClient();");
lines.push("");
lines.push("  useEffect(() => {");
lines.push("    const canvas = canvasRef.current;");
lines.push("    if (!canvas) return;");
lines.push("    const resize = () => { canvas.width = canvas.offsetWidth; canvas.height = canvas.offsetHeight; };");
lines.push("    resize();");
lines.push("    window.addEventListener('resize', resize);");
lines.push("    const ctx = canvas.getContext('2d');");
lines.push("    if (!ctx) return;");
lines.push("    let angle = 0;");
lines.push("    const draw = () => {");
lines.push("      const d = dataRef.current;");
lines.push("      const W = canvas.width, H = canvas.height;");
lines.push("      const cx = W * 0.5, cy = H * 0.5;");
lines.push("      const scale = Math.min(W, H) / 48;");
lines.push("      d.frame++; angle += 0.002;");
lines.push("      ctx.fillStyle = 'rgba(7,8,15,0.05)';");
lines.push("      ctx.fillRect(0, 0, W, H);");
lines.push("      d.pts.forEach((a, ai) => {");
lines.push("        const dx=S*(a.y-a.x), dy=a.x*(R-a.z)-a.y, dz=a.x*a.y-B*a.z;");
lines.push("        a.x+=dx*DT; a.y+=dy*DT; a.z+=dz*DT;");
lines.push("        const rx = a.x*Math.cos(angle) - a.y*Math.sin(angle);");
lines.push("        const px = cx + scale*rx;");
lines.push("        const py = cy - scale*(a.z-25);");
lines.push("        a.trail.push({px,py});");
lines.push("        if (a.trail.length > TRAIL) a.trail.shift();");
lines.push("        const [r,g,b] = COLORS[ai];");
lines.push("        const len = a.trail.length;");
lines.push("        for (let i=2; i<len; i++) {");
lines.push("          const t = i/len;");
lines.push("          ctx.beginPath();");
lines.push("          ctx.moveTo(a.trail[i-1].px, a.trail[i-1].py);");
lines.push("          ctx.lineTo(a.trail[i].px, a.trail[i].py);");
lines.push("          ctx.strokeStyle = 'rgba('+r+','+g+','+b+','+(t*t*t*0.6).toFixed(3)+')';");
lines.push("          ctx.lineWidth = 0.6; ctx.stroke();");
lines.push("        }");
lines.push("        if (len > 0) {");
lines.push("          const last = a.trail[len-1];");
lines.push("          const grd = ctx.createRadialGradient(last.px,last.py,0,last.px,last.py,6);");
lines.push("          grd.addColorStop(0,'rgba('+r+','+g+','+b+',1)');");
lines.push("          grd.addColorStop(1,'rgba('+r+','+g+','+b+',0)');");
lines.push("          ctx.beginPath(); ctx.arc(last.px,last.py,6,0,Math.PI*2); ctx.fillStyle=grd; ctx.fill();");
lines.push("          ctx.beginPath(); ctx.arc(last.px,last.py,1.5,0,Math.PI*2); ctx.fillStyle='#fff'; ctx.fill();");
lines.push("        }");
lines.push("      });");
lines.push("      animRef.current = requestAnimationFrame(draw);");
lines.push("    };");
lines.push("    draw();");
lines.push("    return () => { cancelAnimationFrame(animRef.current); window.removeEventListener('resize', resize); };");
lines.push("  }, []);");
lines.push("");
lines.push("  const handleSubmit = async (e: React.FormEvent) => {");
lines.push("    e.preventDefault();");
lines.push("    setLoading(true); setError('');");
lines.push("    if (mode === 'login') {");
lines.push("      const { error: err } = await supabase.auth.signInWithPassword({ email, password });");
lines.push("      if (err) { setError(err.message); setLoading(false); }");
lines.push("      else router.push('/dashboard');");
lines.push("    } else {");
lines.push("      router.push('/signup');");
lines.push("    }");
lines.push("  };");
lines.push("");
lines.push("  const inp = {");
lines.push("    width:'100%', padding:'11px 14px',");
lines.push("    background:'rgba(255,255,255,0.05)',");
lines.push("    border:'1px solid rgba(99,102,241,0.25)',");
lines.push("    borderRadius:'10px', color:'#F1F5F9', fontSize:'14px',");
lines.push("    outline:'none', boxSizing:'border-box' as const,");
lines.push("    fontFamily:'Inter,sans-serif',");
lines.push("    transition:'border-color 0.2s ease',");
lines.push("  };");
lines.push("");
lines.push("  return (");
lines.push("    <div style={{ width:'100%', height:'100vh', overflow:'hidden', background:'#07080F', fontFamily:\"'Inter',sans-serif\", color:'#F1F5F9', position:'relative' }}>");
lines.push("");
lines.push("      {/* Lorenz Canvas - full viewport */}");
lines.push("      <canvas ref={canvasRef} style={{ position:'absolute', inset:0, width:'100%', height:'100%', zIndex:0 }} />");
lines.push("");
lines.push("      {/* Radial vignette to keep center readable */}");
lines.push("      <div style={{ position:'absolute', inset:0, background:'radial-gradient(ellipse 60% 70% at 50% 50%, rgba(7,8,15,0.75) 0%, rgba(7,8,15,0.2) 100%)', zIndex:1, pointerEvents:'none' }} />");
lines.push("");
lines.push("      {/* Subtle grid overlay */}");
lines.push("      <div style={{ position:'absolute', inset:0, backgroundImage:'linear-gradient(rgba(99,102,241,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(99,102,241,0.03) 1px, transparent 1px)', backgroundSize:'60px 60px', zIndex:1, pointerEvents:'none' }} />");
lines.push("");
lines.push("      {/* Nav */}");
lines.push("      <nav style={{ position:'absolute', top:0, left:0, right:0, zIndex:10, height:'60px', display:'flex', alignItems:'center', justifyContent:'space-between', padding:'0 40px' }}>");
lines.push("        <div style={{ display:'flex', alignItems:'center', gap:'10px' }}>");
lines.push("          <div style={{ width:'32px', height:'32px', borderRadius:'9px', background:'linear-gradient(135deg,#6366F1,#22D3EE)', display:'flex', alignItems:'center', justifyContent:'center', boxShadow:'0 0 20px rgba(99,102,241,0.5)' }}>");
lines.push("            <Zap size={16} color=\"#fff\" />");
lines.push("          </div>");
lines.push("          <span style={{ fontWeight:800, fontSize:'18px', letterSpacing:'-0.5px' }}>PulsarIQ</span>");
lines.push("        </div>");
lines.push("        <div style={{ display:'flex', alignItems:'center', gap:'24px', fontSize:'13px', color:'#64748B' }}>");
lines.push("          <a href=\"#features\" style={{ color:'#64748B', textDecoration:'none' }}>Features</a>");
lines.push("          <a href=\"#how\" style={{ color:'#64748B', textDecoration:'none' }}>How it works</a>");
lines.push("          <a href=\"/signup\" style={{ color:'#22D3EE', textDecoration:'none', fontWeight:600 }}>Create workspace</a>");
lines.push("        </div>");
lines.push("      </nav>");
lines.push("");
lines.push("      {/* Hero - centered, minimal */}");
lines.push("      <div style={{ position:'absolute', inset:0, zIndex:5, display:'flex', alignItems:'center', justifyContent:'center', padding:'0 24px' }}>");
lines.push("        <div style={{ display:'flex', flexDirection:'column', alignItems:'center', gap:'0', width:'100%', maxWidth:'460px' }}>");
lines.push("");
lines.push("          {/* Badge */}");
lines.push("          <div style={{ display:'flex', alignItems:'center', gap:'6px', padding:'4px 12px', borderRadius:'20px', border:'1px solid rgba(34,211,238,0.2)', background:'rgba(34,211,238,0.06)', marginBottom:'24px', fontSize:'11px', color:'#22D3EE', letterSpacing:'1px', fontWeight:600 }}>");
lines.push("            <div style={{ width:'5px', height:'5px', borderRadius:'50%', background:'#22D3EE', boxShadow:'0 0 8px #22D3EE' }} />");
lines.push("            ENTERPRISE DOCUMENT AI");
lines.push("          </div>");
lines.push("");
lines.push("          {/* Headline */}");
lines.push("          <h1 style={{ fontSize:'clamp(36px,5vw,58px)', fontWeight:800, textAlign:'center', margin:'0 0 10px', lineHeight:1.08, letterSpacing:'-2px' }}>");
lines.push("            Your knowledge,");
lines.push("            <br />");
lines.push("            <span style={{ background:'linear-gradient(90deg,#6366F1,#22D3EE)', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent' }}>pulsing with intelligence.</span>");
lines.push("          </h1>");
lines.push("");
lines.push("          <p style={{ fontSize:'15px', color:'#64748B', textAlign:'center', margin:'0 0 32px', lineHeight:1.6 }}>");
lines.push("            Upload any document. Ask any question. Get precise answers with citations.");
lines.push("          </p>");
lines.push("");
lines.push("          {/* Embedded auth form */}");
lines.push("          <div style={{ width:'100%', padding:'28px', borderRadius:'16px', background:'rgba(13,15,28,0.85)', border:'1px solid rgba(99,102,241,0.2)', backdropFilter:'blur(32px)', boxShadow:'0 24px 64px rgba(0,0,0,0.5)' }}>");
lines.push("");
lines.push("            {/* Mode toggle */}");
lines.push("            <div style={{ display:'flex', gap:'0', marginBottom:'22px', background:'rgba(255,255,255,0.04)', borderRadius:'10px', padding:'3px' }}>");
lines.push("              {(['login','signup'] as const).map(m => (");
lines.push("                <button key={m} onClick={() => { setMode(m); setError(''); }} style={{ flex:1, padding:'8px', borderRadius:'8px', background:mode===m ? 'linear-gradient(135deg,#6366F1,#22D3EE)' : 'transparent', border:'none', color:mode===m ? '#fff' : '#64748B', fontSize:'13px', fontWeight:mode===m ? 700 : 400, cursor:'pointer', transition:'all 0.2s' }}>");
lines.push("                  {m === 'login' ? 'Sign In' : 'Create Workspace'}");
lines.push("                </button>");
lines.push("              ))}");
lines.push("            </div>");
lines.push("");
lines.push("            <form onSubmit={handleSubmit} style={{ display:'flex', flexDirection:'column', gap:'12px' }}>");
lines.push("              <div>");
lines.push("                <label style={{ fontSize:'12px', color:'#64748B', display:'block', marginBottom:'6px' }}>Work Email</label>");
lines.push("                <input type=\"email\" required value={email} onChange={e => setEmail(e.target.value)} placeholder=\"you@company.com\" style={inp} />");
lines.push("              </div>");
lines.push("              {mode === 'login' && (");
lines.push("                <div>");
lines.push("                  <label style={{ fontSize:'12px', color:'#64748B', display:'block', marginBottom:'6px' }}>Password</label>");
lines.push("                  <input type=\"password\" required value={password} onChange={e => setPassword(e.target.value)} placeholder=\"••••••••\" style={inp} />");
lines.push("                </div>");
lines.push("              )}");
lines.push("              {error && (");
lines.push("                <div style={{ fontSize:'12px', color:'#EF4444', padding:'8px 12px', background:'rgba(239,68,68,0.08)', borderRadius:'8px', border:'1px solid rgba(239,68,68,0.2)' }}>{error}</div>");
lines.push("              )}");
lines.push("              <button type=\"submit\" disabled={loading} style={{ padding:'12px', borderRadius:'10px', background:'linear-gradient(135deg,#6366F1,#22D3EE)', border:'none', color:'#fff', fontSize:'14px', fontWeight:700, cursor:loading ? 'wait' : 'pointer', opacity:loading ? 0.7 : 1, boxShadow:'0 4px 20px rgba(99,102,241,0.4)', display:'flex', alignItems:'center', justifyContent:'center', gap:'8px', marginTop:'4px' }}>");
lines.push("                {loading ? 'Please wait...' : mode === 'login' ? 'Sign In to PulsarIQ' : 'Continue'}");
lines.push("                {!loading && <ArrowRight size={15} />}");
lines.push("              </button>");
lines.push("            </form>");
lines.push("");
lines.push("            <p style={{ textAlign:'center', fontSize:'12px', color:'#334155', marginTop:'16px', marginBottom:0 }}>");
lines.push("              {mode === 'login' ? 'New to PulsarIQ? ' : 'Already have an account? '}");
lines.push("              <span onClick={() => { setMode(mode === 'login' ? 'signup' : 'login'); setError(''); }} style={{ color:'#6366F1', cursor:'pointer', fontWeight:600 }}>");
lines.push("                {mode === 'login' ? 'Create workspace' : 'Sign in'}");
lines.push("              </span>");
lines.push("            </p>");
lines.push("          </div>");
lines.push("");
lines.push("          {/* Trust line */}");
lines.push("          <p style={{ fontSize:'11px', color:'#334155', marginTop:'16px', textAlign:'center' }}>");
lines.push("            Self-hosted &#183; Zero data exposure &#183; Enterprise RBAC");
lines.push("          </p>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("");
lines.push("      {/* Scroll indicator */}");
lines.push("      <div style={{ position:'absolute', bottom:'28px', left:'50%', transform:'translateX(-50%)', zIndex:10, display:'flex', flexDirection:'column', alignItems:'center', gap:'6px' }}>");
lines.push("        <span style={{ fontSize:'10px', color:'#334155', letterSpacing:'2px' }}>EXPLORE</span>");
lines.push("        <ChevronDown size={16} color=\"#334155\" />");
lines.push("      </div>");
lines.push("    </div>");
lines.push("  );");
lines.push("}");

write('app/page.tsx', lines.join('\n'));

console.log('\n  \u2705 Phase 5C complete!\n');
console.log('  Run: rmdir /s /q .next && npm run dev');
console.log('  Open: http://localhost:3000\n');
