// PulsarIQ — Phase 5B Fix: Premium Landing Page
// Run: node phase5bfix.js

const fs   = require('fs');
const path = require('path');
const root = process.cwd();

function write(filePath, content) {
  const full = path.join(root, filePath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content, 'utf8');
  console.log('  \u2713', filePath);
}

console.log('\n  PulsarIQ \u2014 Phase 5B: Premium Landing Page\n');

// Add marquee animation to globals.css
const globalsCss = fs.readFileSync(path.join(root, 'app', 'globals.css'), 'utf8');
if (!globalsCss.includes('marquee')) {
  fs.appendFileSync(
    path.join(root, 'app', 'globals.css'),
    '\n@keyframes marquee { 0% { transform:translateX(0) } 100% { transform:translateX(-50%) } }\n'
  );
  console.log('  \u2713 globals.css (marquee animation added)');
}

// Build page content using string concatenation (avoids backtick issues)
const lines = [];
lines.push("'use client';");
lines.push("import { useEffect, useRef } from 'react';");
lines.push("import { ArrowRight, Shield, Database, MessageSquare, FileText, Users, Lock, Zap, BarChart2, Check } from 'lucide-react';");
lines.push("");
lines.push("const S=10,R=28,B=8/3,DT=0.005,TRAIL=900;");
lines.push("const SEEDS=[{x:0.1,y:0,z:0},{x:0.12,y:0.02,z:0.1},{x:-0.1,y:0.01,z:0},{x:0.05,y:-0.05,z:0.2}];");
lines.push("const COLORS=[[99,102,241],[34,211,238],[168,85,247],[34,211,238]];");
lines.push("");
lines.push("export default function LandingPage() {");
lines.push("  const canvasRef = useRef<HTMLCanvasElement>(null);");
lines.push("  const dataRef = useRef<{frame:number;pts:{x:number;y:number;z:number;trail:{px:number;py:number}[]}[]}>(");
lines.push("    { frame:0, pts: SEEDS.map(s => ({ ...s, trail:[] })) }");
lines.push("  );");
lines.push("  const animRef = useRef<number>(0);");
lines.push("");
lines.push("  useEffect(() => {");
lines.push("    const canvas = canvasRef.current;");
lines.push("    if (!canvas) return;");
lines.push("    const resize = () => { canvas.width = canvas.offsetWidth; canvas.height = canvas.offsetHeight; };");
lines.push("    resize();");
lines.push("    window.addEventListener('resize', resize);");
lines.push("    const ctx = canvas.getContext('2d');");
lines.push("    if (!ctx) return;");
lines.push("    let angle = 0;");
lines.push("    const draw = () => {");
lines.push("      const d = dataRef.current;");
lines.push("      const W = canvas.width, H = canvas.height;");
lines.push("      const cx = W * 0.5, cy = H * 0.44;");
lines.push("      const scale = Math.min(W, H) / 52;");
lines.push("      d.frame++; angle += 0.0025;");
lines.push("      ctx.fillStyle = 'rgba(7,8,15,0.04)';");
lines.push("      ctx.fillRect(0, 0, W, H);");
lines.push("      d.pts.forEach((a, ai) => {");
lines.push("        const dx=S*(a.y-a.x), dy=a.x*(R-a.z)-a.y, dz=a.x*a.y-B*a.z;");
lines.push("        a.x+=dx*DT; a.y+=dy*DT; a.z+=dz*DT;");
lines.push("        const rx = a.x*Math.cos(angle) - a.y*Math.sin(angle);");
lines.push("        const px = cx + scale*rx;");
lines.push("        const py = cy - scale*(a.z-25);");
lines.push("        a.trail.push({px,py});");
lines.push("        if (a.trail.length > TRAIL) a.trail.shift();");
lines.push("        const [r,g,b] = COLORS[ai];");
lines.push("        const len = a.trail.length;");
lines.push("        for (let i=2; i<len; i++) {");
lines.push("          const t = i/len;");
lines.push("          ctx.beginPath();");
lines.push("          ctx.moveTo(a.trail[i-1].px, a.trail[i-1].py);");
lines.push("          ctx.lineTo(a.trail[i].px, a.trail[i].py);");
lines.push("          ctx.strokeStyle = 'rgba('+r+','+g+','+b+','+(t*t*0.45).toFixed(3)+')';");
lines.push("          ctx.lineWidth = 0.7; ctx.stroke();");
lines.push("        }");
lines.push("        if (len > 0) {");
lines.push("          const last = a.trail[len-1];");
lines.push("          const grd = ctx.createRadialGradient(last.px,last.py,0,last.px,last.py,5);");
lines.push("          grd.addColorStop(0,'rgba('+r+','+g+','+b+',0.9)');");
lines.push("          grd.addColorStop(1,'rgba('+r+','+g+','+b+',0)');");
lines.push("          ctx.beginPath(); ctx.arc(last.px,last.py,5,0,Math.PI*2); ctx.fillStyle=grd; ctx.fill();");
lines.push("          ctx.beginPath(); ctx.arc(last.px,last.py,1.2,0,Math.PI*2); ctx.fillStyle='rgba(255,255,255,0.95)'; ctx.fill();");
lines.push("        }");
lines.push("      });");
lines.push("      animRef.current = requestAnimationFrame(draw);");
lines.push("    };");
lines.push("    draw();");
lines.push("    return () => { cancelAnimationFrame(animRef.current); window.removeEventListener('resize', resize); };");
lines.push("  }, []);");
lines.push("");
lines.push("  const LOGOS = ['Microsoft','Salesforce','Atlassian','Oracle','SAP','Notion','Slack','HubSpot','Stripe','Twilio'];");
lines.push("  const FEATURES = [");
lines.push("    { icon:Database,      title:'RAG Pipeline',    desc:'Upload once, query forever. Exact source citations every time.',                color:'#6366F1', span:2 },");
lines.push("    { icon:Lock,          title:'100% Private',    desc:'Self-hosted AI. Your documents never leave your servers.',                       color:'#A855F7', span:1 },");
lines.push("    { icon:Users,         title:'RBAC',            desc:'Admin, Manager, Viewer roles across unlimited organisations.',                   color:'#22D3EE', span:1 },");
lines.push("    { icon:FileText,      title:'Every Format',    desc:'PDF, DOCX, XLSX, PPTX, CSV, TXT, HTML.',                                        color:'#F59E0B', span:1 },");
lines.push("    { icon:MessageSquare, title:'AI Chat',         desc:'Real-time streaming answers grounded in your documents.',                        color:'#EC4899', span:2 },");
lines.push("    { icon:BarChart2,     title:'Analytics',       desc:'Usage insights, query trends, document performance.',                            color:'#10B981', span:1 },");
lines.push("  ];");
lines.push("  const STEPS = [");
lines.push("    { n:'01', title:'Upload Your Documents',   desc:'Drag and drop any file type. PDF, DOCX, Excel, PowerPoint, CSV up to 50MB each.' },");
lines.push("    { n:'02', title:'AI Processes & Indexes',  desc:'PulsarIQ automatically parses, chunks, and embeds your documents. Status updates in real-time.' },");
lines.push("    { n:'03', title:'Ask Anything',            desc:'Chat with your knowledge base. Get precise answers with exact source citations and page numbers.' },");
lines.push("  ];");
lines.push("  const TESTIMONIALS = [");
lines.push("    { quote:'PulsarIQ transformed how our legal team processes 10,000+ documents. What took days now takes minutes with precise citations.', name:'Sarah Chen', role:'CTO, Meridian Legal', avatar:'SC' },");
lines.push("    { quote:'Finally an AI document platform that keeps our sensitive data on-premise. The RBAC system is exactly what enterprise needs.', name:'Marcus Webb', role:'VP Engineering, FinCore', avatar:'MW' },");
lines.push("    { quote:'The citation accuracy is remarkable. We can trust every AI answer because it traces back to the exact source document.', name:'Priya Nair', role:'Head of Innovation, Altara', avatar:'PN' },");
lines.push("  ];");
lines.push("");
lines.push("  return (");
lines.push("    <div style={{ width:'100%', background:'#07080F', fontFamily:\"'Inter','SF Pro Display',sans-serif\", color:'#F1F5F9', overflowX:'hidden' }}>");
lines.push("      <div style={{ position:'relative', minHeight:'100vh', display:'flex', flexDirection:'column' }}>");
lines.push("        <canvas ref={canvasRef} style={{ position:'absolute', inset:0, width:'100%', height:'100%' }} />");
lines.push("        <div style={{ position:'absolute', inset:0, background:'radial-gradient(ellipse at 50% 40%, transparent 20%, rgba(7,8,15,0.6) 100%)', pointerEvents:'none' }} />");
lines.push("        <div style={{ position:'absolute', bottom:0, left:0, right:0, height:'200px', background:'linear-gradient(to bottom,transparent,#07080F)', pointerEvents:'none', zIndex:3 }} />");
lines.push("        <nav style={{ position:'relative', zIndex:10, height:'62px', display:'flex', alignItems:'center', justifyContent:'space-between', padding:'0 48px', backdropFilter:'blur(20px)', background:'rgba(7,8,15,0.5)', borderBottom:'1px solid rgba(99,102,241,0.08)' }}>");
lines.push("          <div style={{ display:'flex', alignItems:'center', gap:'10px' }}>");
lines.push("            <div style={{ width:'34px', height:'34px', borderRadius:'10px', background:'linear-gradient(135deg,#6366F1,#22D3EE)', display:'flex', alignItems:'center', justifyContent:'center', boxShadow:'0 0 20px rgba(99,102,241,0.5)' }}>");
lines.push("              <Zap size={17} color=\"#fff\" />");
lines.push("            </div>");
lines.push("            <div><div style={{ fontWeight:800, fontSize:'16px', lineHeight:1 }}>PulsarIQ</div><div style={{ fontSize:'9px', color:'#64748B', letterSpacing:'1.2px' }}>ENTERPRISE AI</div></div>");
lines.push("          </div>");
lines.push("          <div style={{ display:'flex', gap:'34px' }}>");
lines.push("            {['Features','How it Works','Pricing','Docs'].map(t => (<span key={t} style={{ fontSize:'13px', color:'#64748B', cursor:'pointer' }}>{t}</span>))}");
lines.push("          </div>");
lines.push("          <div style={{ display:'flex', gap:'10px' }}>");
lines.push("            <a href=\"/login\"  style={{ padding:'8px 18px', borderRadius:'8px', border:'1px solid rgba(255,255,255,0.08)', background:'transparent', color:'#94A3B8', fontSize:'13px', textDecoration:'none' }}>Sign In</a>");
lines.push("            <a href=\"/signup\" style={{ display:'flex', alignItems:'center', gap:'6px', padding:'8px 20px', borderRadius:'9px', background:'linear-gradient(135deg,#6366F1,#22D3EE)', color:'#fff', fontSize:'13px', fontWeight:700, textDecoration:'none' }}>Get Started <ArrowRight size={14} /></a>");
lines.push("          </div>");
lines.push("        </nav>");
lines.push("        <div style={{ position:'relative', zIndex:5, flex:1, display:'flex', alignItems:'center', padding:'0 48px', gap:'60px', maxWidth:'1200px', margin:'0 auto', width:'100%' }}>");
lines.push("          <div style={{ flex:'0 0 520px' }}>");
lines.push("            <div style={{ display:'inline-flex', alignItems:'center', gap:'7px', padding:'5px 14px', borderRadius:'30px', border:'1px solid rgba(34,211,238,0.3)', background:'rgba(34,211,238,0.07)', marginBottom:'28px', fontSize:'11px', color:'#22D3EE', fontWeight:600 }}>");
lines.push("              <div style={{ width:'5px', height:'5px', borderRadius:'50%', background:'#22D3EE', boxShadow:'0 0 8px #22D3EE' }} />");
lines.push("              SELF-HOSTED ENTERPRISE AI");
lines.push("            </div>");
lines.push("            <h1 style={{ fontSize:'clamp(40px,4vw,64px)', fontWeight:800, lineHeight:1.05, margin:'0 0 20px', letterSpacing:'-2px' }}>");
lines.push("              Your enterprise knowledge,{' '}<span style={{ background:'linear-gradient(90deg,#6366F1,#22D3EE)', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent' }}>finally intelligent.</span>");
lines.push("            </h1>");
lines.push("            <p style={{ fontSize:'17px', color:'#64748B', lineHeight:1.7, margin:'0 0 36px', maxWidth:'440px' }}>Upload any document. Ask any question. PulsarIQ finds the exact answer in your knowledge base with precise citations, every time.</p>");
lines.push("            <div style={{ display:'flex', gap:'12px', marginBottom:'32px' }}>");
lines.push("              <a href=\"/signup\" style={{ display:'flex', alignItems:'center', gap:'8px', padding:'13px 28px', borderRadius:'12px', background:'linear-gradient(135deg,#6366F1,#22D3EE)', color:'#fff', fontSize:'14px', fontWeight:700, textDecoration:'none', boxShadow:'0 8px 32px rgba(99,102,241,0.4)' }}>Start Free Trial <ArrowRight size={15} /></a>");
lines.push("              <a href=\"/dashboard\" style={{ padding:'13px 24px', borderRadius:'12px', background:'rgba(255,255,255,0.04)', border:'1px solid rgba(255,255,255,0.08)', color:'#F1F5F9', fontSize:'14px', textDecoration:'none' }}>Open Dashboard</a>");
lines.push("            </div>");
lines.push("            <div style={{ display:'flex', gap:'20px' }}>");
lines.push("              {[{icon:Shield,label:'SOC2 Ready'},{icon:Database,label:'pgvector'},{icon:Lock,label:'On-Premise'}].map(({icon:Icon,label}) => (");
lines.push("                <div key={label} style={{ display:'flex', alignItems:'center', gap:'6px', fontSize:'12px', color:'#475569' }}><Icon size={12} color=\"#6366F1\" />{label}</div>");
lines.push("              ))}");
lines.push("            </div>");
lines.push("          </div>");
lines.push("          <div style={{ flex:1, position:'relative' }}>");
lines.push("            <div style={{ borderRadius:'16px', background:'rgba(13,15,28,0.9)', border:'1px solid rgba(99,102,241,0.2)', backdropFilter:'blur(24px)', overflow:'hidden', boxShadow:'0 32px 64px rgba(0,0,0,0.6)', transform:'perspective(1200px) rotateY(-6deg) rotateX(3deg)' }}>");
lines.push("              <div style={{ height:'44px', display:'flex', alignItems:'center', justifyContent:'space-between', padding:'0 16px', borderBottom:'1px solid rgba(99,102,241,0.12)', background:'rgba(7,8,15,0.8)' }}>");
lines.push("                <div style={{ display:'flex', alignItems:'center', gap:'8px' }}>");
lines.push("                  <div style={{ width:'24px', height:'24px', borderRadius:'7px', background:'linear-gradient(135deg,#6366F1,#22D3EE)', display:'flex', alignItems:'center', justifyContent:'center' }}><Zap size={12} color=\"#fff\" /></div>");
lines.push("                  <span style={{ fontSize:'12px', fontWeight:700 }}>PulsarIQ</span>");
lines.push("                </div>");
lines.push("                <div style={{ display:'flex', gap:'6px' }}>{['#EF4444','#F59E0B','#22C55E'].map(c => <div key={c} style={{ width:'10px', height:'10px', borderRadius:'50%', background:c }} />)}</div>");
lines.push("              </div>");
lines.push("              <div style={{ display:'flex', height:'340px' }}>");
lines.push("                <div style={{ width:'140px', borderRight:'1px solid rgba(99,102,241,0.1)', padding:'12px 8px', display:'flex', flexDirection:'column', gap:'3px' }}>");
lines.push("                  {[{icon:BarChart2,l:'Dashboard'},{icon:FileText,l:'Documents',a:true},{icon:MessageSquare,l:'AI Chat'},{icon:Shield,l:'Access'}].map(({icon:Icon,l,a}) => (");
lines.push("                    <div key={l} style={{ display:'flex', alignItems:'center', gap:'7px', padding:'6px 8px', borderRadius:'6px', background:a ? 'rgba(99,102,241,0.1)' : 'transparent' }}>");
lines.push("                      <Icon size={11} color={a ? '#6366F1' : '#475569'} />");
lines.push("                      <span style={{ fontSize:'11px', color:a ? '#F1F5F9' : '#475569' }}>{l}</span>");
lines.push("                    </div>");
lines.push("                  ))}");
lines.push("                </div>");
lines.push("                <div style={{ flex:1, padding:'14px', display:'flex', flexDirection:'column', gap:'10px' }}>");
lines.push("                  <div style={{ display:'flex', gap:'8px' }}>");
lines.push("                    {[{l:'Documents',v:'2,847'},{l:'AI Queries',v:'3,419'},{l:'Chunks',v:'1.2M'}].map(({l,v}) => (");
lines.push("                      <div key={l} style={{ flex:1, padding:'10px', borderRadius:'8px', background:'rgba(255,255,255,0.03)', border:'1px solid rgba(99,102,241,0.1)' }}>");
lines.push("                        <div style={{ fontSize:'9px', color:'#475569', marginBottom:'4px' }}>{l}</div>");
lines.push("                        <div style={{ fontSize:'18px', fontWeight:800, color:'#F1F5F9' }}>{v}</div>");
lines.push("                      </div>");
lines.push("                    ))}");
lines.push("                  </div>");
lines.push("                  <div style={{ borderRadius:'8px', background:'rgba(255,255,255,0.02)', border:'1px solid rgba(99,102,241,0.08)', overflow:'hidden', flex:1 }}>");
lines.push("                    {[{n:'Q4 Financial Report.pdf',s:'Ready',t:'PDF'},{n:'Product Roadmap.pptx',s:'Indexing',t:'PPT'},{n:'Compliance Manual.docx',s:'Ready',t:'DOC'}].map((d,i) => (");
lines.push("                      <div key={i} style={{ display:'flex', alignItems:'center', gap:'8px', padding:'8px 10px', borderBottom:i<2 ? '1px solid rgba(99,102,241,0.06)' : 'none' }}>");
lines.push("                        <div style={{ fontSize:'8px', fontWeight:700, color:'#6366F1', width:'24px', height:'24px', borderRadius:'5px', background:'rgba(99,102,241,0.1)', display:'flex', alignItems:'center', justifyContent:'center' }}>{d.t}</div>");
lines.push("                        <span style={{ flex:1, fontSize:'10px', color:'#94A3B8', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}>{d.n}</span>");
lines.push("                        <div style={{ fontSize:'9px', color:d.s==='Ready' ? '#22C55E' : '#6366F1', padding:'1px 6px', borderRadius:'10px', background:d.s==='Ready' ? 'rgba(34,197,94,0.1)' : 'rgba(99,102,241,0.1)' }}>{d.s}</div>");
lines.push("                      </div>");
lines.push("                    ))}");
lines.push("                  </div>");
lines.push("                  <div style={{ padding:'8px 10px', borderRadius:'8px', background:'rgba(99,102,241,0.06)', border:'1px solid rgba(99,102,241,0.15)' }}>");
lines.push("                    <div style={{ fontSize:'9px', color:'#94A3B8', marginBottom:'4px' }}>\"What was Q4 revenue growth?\"</div>");
lines.push("                    <div style={{ fontSize:'9px', color:'#F1F5F9', lineHeight:1.4 }}>Revenue reached $47.3M, a 23% YoY increase. <span style={{ color:'#22D3EE' }}>[Q4 Report, p.12]</span></div>");
lines.push("                  </div>");
lines.push("                </div>");
lines.push("              </div>");
lines.push("            </div>");
lines.push("          </div>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      <div style={{ borderTop:'1px solid rgba(255,255,255,0.05)', borderBottom:'1px solid rgba(255,255,255,0.05)', padding:'20px 0', overflow:'hidden', background:'rgba(255,255,255,0.01)' }}>");
lines.push("        <p style={{ textAlign:'center', fontSize:'11px', color:'#334155', letterSpacing:'2px', fontWeight:600, marginBottom:'16px' }}>TRUSTED BY LEADING ENTERPRISES</p>");
lines.push("        <div style={{ display:'flex', gap:'48px', animation:'marquee 20s linear infinite', whiteSpace:'nowrap' }}>");
lines.push("          {[...LOGOS,...LOGOS].map((l,i) => (<span key={i} style={{ fontSize:'14px', fontWeight:700, color:'#334155', letterSpacing:'1px', flexShrink:0 }}>{l}</span>))}");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      <div style={{ padding:'100px 48px', maxWidth:'1100px', margin:'0 auto' }}>");
lines.push("        <div style={{ marginBottom:'60px' }}>");
lines.push("          <p style={{ fontSize:'11px', color:'#6366F1', letterSpacing:'2.5px', fontWeight:700, marginBottom:'12px' }}>CAPABILITIES</p>");
lines.push("          <h2 style={{ fontSize:'clamp(32px,3.5vw,48px)', fontWeight:800, margin:'0 0 16px', letterSpacing:'-1.5px', maxWidth:'600px' }}>Everything your enterprise needs in one platform</h2>");
lines.push("          <p style={{ fontSize:'16px', color:'#64748B', maxWidth:'500px', lineHeight:1.65 }}>Built for the demands of modern enterprise - private, fast, and intelligent.</p>");
lines.push("        </div>");
lines.push("        <div style={{ display:'grid', gridTemplateColumns:'repeat(3,1fr)', gap:'12px' }}>");
lines.push("          {FEATURES.map(({ icon:Icon, title, desc, color, span }) => (");
lines.push("            <div key={title} style={{ gridColumn:'span '+span, padding:'28px', borderRadius:'16px', background:'rgba(255,255,255,0.03)', border:'1px solid rgba(99,102,241,0.1)', backdropFilter:'blur(16px)', position:'relative', overflow:'hidden' }}>");
lines.push("              <div style={{ position:'absolute', top:'-30px', right:'-30px', width:'120px', height:'120px', borderRadius:'50%', background:'radial-gradient(circle,'+color+'12,transparent)', pointerEvents:'none' }} />");
lines.push("              <div style={{ width:'44px', height:'44px', borderRadius:'12px', background:color+'14', border:'1px solid '+color+'22', display:'flex', alignItems:'center', justifyContent:'center', marginBottom:'16px' }}><Icon size={20} color={color} /></div>");
lines.push("              <h3 style={{ fontSize:'16px', fontWeight:700, margin:'0 0 8px' }}>{title}</h3>");
lines.push("              <p style={{ fontSize:'13px', color:'#64748B', lineHeight:1.6, margin:0 }}>{desc}</p>");
lines.push("            </div>");
lines.push("          ))}");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      <div style={{ padding:'80px 48px', background:'rgba(255,255,255,0.01)', borderTop:'1px solid rgba(255,255,255,0.04)' }}>");
lines.push("        <div style={{ maxWidth:'1100px', margin:'0 auto' }}>");
lines.push("          <div style={{ textAlign:'center', marginBottom:'60px' }}>");
lines.push("            <p style={{ fontSize:'11px', color:'#22D3EE', letterSpacing:'2.5px', fontWeight:700, marginBottom:'12px' }}>HOW IT WORKS</p>");
lines.push("            <h2 style={{ fontSize:'clamp(28px,3vw,42px)', fontWeight:800, margin:0, letterSpacing:'-1px' }}>Three steps to intelligence</h2>");
lines.push("          </div>");
lines.push("          <div style={{ display:'grid', gridTemplateColumns:'repeat(3,1fr)', gap:'24px' }}>");
lines.push("            {STEPS.map(({n,title,desc}) => (");
lines.push("              <div key={n} style={{ padding:'32px', borderRadius:'16px', background:'rgba(255,255,255,0.02)', border:'1px solid rgba(99,102,241,0.1)' }}>");
lines.push("                <div style={{ fontSize:'48px', fontWeight:900, color:'rgba(99,102,241,0.12)', lineHeight:1, marginBottom:'16px', letterSpacing:'-2px' }}>{n}</div>");
lines.push("                <h3 style={{ fontSize:'16px', fontWeight:700, margin:'0 0 10px' }}>{title}</h3>");
lines.push("                <p style={{ fontSize:'13px', color:'#64748B', lineHeight:1.65, margin:0 }}>{desc}</p>");
lines.push("              </div>");
lines.push("            ))}");
lines.push("          </div>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      <div style={{ padding:'80px 48px', maxWidth:'1100px', margin:'0 auto' }}>");
lines.push("        <div style={{ display:'grid', gridTemplateColumns:'repeat(4,1fr)', gap:'1px', background:'rgba(255,255,255,0.05)', borderRadius:'16px', overflow:'hidden' }}>");
lines.push("          {[{v:'99.9%',l:'Uptime SLA'},{v:'<200ms',l:'Search Speed'},{v:'7',l:'File Formats'},{v:'384D',l:'Vector Embeddings'}].map(({v,l}) => (");
lines.push("            <div key={l} style={{ padding:'32px 24px', background:'#07080F', textAlign:'center' }}>");
lines.push("              <div style={{ fontSize:'36px', fontWeight:900, background:'linear-gradient(135deg,#6366F1,#22D3EE)', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', letterSpacing:'-1px', marginBottom:'6px' }}>{v}</div>");
lines.push("              <div style={{ fontSize:'13px', color:'#475569' }}>{l}</div>");
lines.push("            </div>");
lines.push("          ))}");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      <div style={{ padding:'80px 48px', background:'rgba(255,255,255,0.01)', borderTop:'1px solid rgba(255,255,255,0.04)' }}>");
lines.push("        <div style={{ maxWidth:'1100px', margin:'0 auto' }}>");
lines.push("          <div style={{ textAlign:'center', marginBottom:'48px' }}>");
lines.push("            <p style={{ fontSize:'11px', color:'#6366F1', letterSpacing:'2.5px', fontWeight:700, marginBottom:'12px' }}>TESTIMONIALS</p>");
lines.push("            <h2 style={{ fontSize:'clamp(28px,3vw,40px)', fontWeight:800, margin:0, letterSpacing:'-1px' }}>Trusted by enterprise teams</h2>");
lines.push("          </div>");
lines.push("          <div style={{ display:'grid', gridTemplateColumns:'repeat(3,1fr)', gap:'16px' }}>");
lines.push("            {TESTIMONIALS.map(({quote,name,role,avatar}) => (");
lines.push("              <div key={name} style={{ padding:'28px', borderRadius:'16px', background:'rgba(255,255,255,0.03)', border:'1px solid rgba(99,102,241,0.1)' }}>");
lines.push("                <div style={{ display:'flex', gap:'4px', marginBottom:'16px' }}>{[1,2,3,4,5].map(s => <span key={s} style={{ color:'#F59E0B', fontSize:'14px' }}>&#9733;</span>)}</div>");
lines.push("                <p style={{ fontSize:'14px', color:'#94A3B8', lineHeight:1.7, margin:'0 0 20px' }}>&#34;{quote}&#34;</p>");
lines.push("                <div style={{ display:'flex', alignItems:'center', gap:'10px' }}>");
lines.push("                  <div style={{ width:'36px', height:'36px', borderRadius:'50%', background:'linear-gradient(135deg,#6366F1,#22D3EE)', display:'flex', alignItems:'center', justifyContent:'center', fontSize:'12px', fontWeight:700, color:'#fff', flexShrink:0 }}>{avatar}</div>");
lines.push("                  <div><div style={{ fontSize:'13px', fontWeight:700, color:'#F1F5F9' }}>{name}</div><div style={{ fontSize:'11px', color:'#64748B' }}>{role}</div></div>");
lines.push("                </div>");
lines.push("              </div>");
lines.push("            ))}");
lines.push("          </div>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      <div style={{ padding:'80px 48px', maxWidth:'1100px', margin:'0 auto' }}>");
lines.push("        <div style={{ textAlign:'center', marginBottom:'48px' }}>");
lines.push("          <p style={{ fontSize:'11px', color:'#22D3EE', letterSpacing:'2.5px', fontWeight:700, marginBottom:'12px' }}>PRICING</p>");
lines.push("          <h2 style={{ fontSize:'clamp(28px,3vw,40px)', fontWeight:800, margin:0, letterSpacing:'-1px' }}>Simple, transparent pricing</h2>");
lines.push("        </div>");
lines.push("        <div style={{ display:'grid', gridTemplateColumns:'repeat(3,1fr)', gap:'16px', alignItems:'start' }}>");
lines.push("          {[");
lines.push("            { tier:'Starter', price:'$49', period:'/month', features:['5 users','100 documents','5GB storage','AI Chat','Email support'], highlight:false },");
lines.push("            { tier:'Business', price:'$149', period:'/month', features:['25 users','1,000 documents','50GB storage','AI Chat + Analytics','Priority support','Custom RBAC'], highlight:true },");
lines.push("            { tier:'Enterprise', price:'Custom', period:'', features:['Unlimited users','Unlimited documents','Unlimited storage','Full feature suite','Dedicated support','On-premise deploy'], highlight:false },");
lines.push("          ].map(({tier,price,period,features,highlight}) => (");
lines.push("            <div key={tier} style={{ padding:'32px', borderRadius:'16px', background:highlight ? 'linear-gradient(135deg,rgba(99,102,241,0.15),rgba(34,211,238,0.08))' : 'rgba(255,255,255,0.02)', border:'1px solid '+(highlight ? 'rgba(99,102,241,0.4)' : 'rgba(99,102,241,0.1)'), position:'relative' }}>");
lines.push("              {highlight && <div style={{ position:'absolute', top:'-12px', left:'50%', transform:'translateX(-50%)', padding:'3px 16px', borderRadius:'20px', background:'linear-gradient(135deg,#6366F1,#22D3EE)', fontSize:'11px', fontWeight:700, color:'#fff' }}>MOST POPULAR</div>}");
lines.push("              <div style={{ fontSize:'14px', fontWeight:600, color:'#64748B', marginBottom:'8px' }}>{tier}</div>");
lines.push("              <div style={{ display:'flex', alignItems:'baseline', gap:'4px', marginBottom:'24px' }}>");
lines.push("                <span style={{ fontSize:'40px', fontWeight:900, color:'#F1F5F9', letterSpacing:'-1px' }}>{price}</span>");
lines.push("                <span style={{ fontSize:'14px', color:'#64748B' }}>{period}</span>");
lines.push("              </div>");
lines.push("              <div style={{ display:'flex', flexDirection:'column', gap:'10px', marginBottom:'24px' }}>");
lines.push("                {features.map(f => (<div key={f} style={{ display:'flex', alignItems:'center', gap:'8px' }}><Check size={14} color=\"#22C55E\" /><span style={{ fontSize:'13px', color:'#94A3B8' }}>{f}</span></div>))}");
lines.push("              </div>");
lines.push("              <a href=\"/signup\" style={{ display:'block', textAlign:'center', padding:'11px', borderRadius:'10px', background:highlight ? 'linear-gradient(135deg,#6366F1,#22D3EE)' : 'rgba(255,255,255,0.06)', border:highlight ? 'none' : '1px solid rgba(255,255,255,0.1)', color:'#fff', fontSize:'14px', fontWeight:600, textDecoration:'none' }}>");
lines.push("                {tier === 'Enterprise' ? 'Contact Us' : 'Start Free Trial'}");
lines.push("              </a>");
lines.push("            </div>");
lines.push("          ))}");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      <div style={{ padding:'80px 48px 0', borderTop:'1px solid rgba(255,255,255,0.04)', position:'relative', overflow:'hidden' }}>");
lines.push("        <div style={{ position:'absolute', top:'50%', left:'50%', transform:'translate(-50%,-50%)', width:'800px', height:'400px', background:'radial-gradient(ellipse, rgba(99,102,241,0.12), transparent)', pointerEvents:'none' }} />");
lines.push("        <div style={{ maxWidth:'800px', margin:'0 auto', textAlign:'center', position:'relative', zIndex:2, paddingBottom:'60px' }}>");
lines.push("          <p style={{ fontSize:'11px', color:'#6366F1', letterSpacing:'2.5px', fontWeight:700, marginBottom:'16px' }}>START TODAY</p>");
lines.push("          <h2 style={{ fontSize:'clamp(32px,4vw,52px)', fontWeight:800, margin:'0 0 16px', letterSpacing:'-1.5px', lineHeight:1.1 }}>Ready to make your knowledge <span style={{ background:'linear-gradient(90deg,#6366F1,#22D3EE)', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent' }}>truly intelligent?</span></h2>");
lines.push("          <p style={{ fontSize:'16px', color:'#64748B', margin:'0 0 36px', lineHeight:1.7 }}>Join the enterprises already using PulsarIQ to transform how their teams interact with documents.</p>");
lines.push("          <a href=\"/signup\" style={{ display:'inline-flex', alignItems:'center', gap:'8px', padding:'14px 36px', borderRadius:'12px', background:'linear-gradient(135deg,#6366F1,#22D3EE)', color:'#fff', fontSize:'15px', fontWeight:700, textDecoration:'none', boxShadow:'0 8px 36px rgba(99,102,241,0.4)' }}>Start Free - No Credit Card <ArrowRight size={16} /></a>");
lines.push("        </div>");
lines.push("        <div style={{ position:'relative', overflow:'hidden', height:'160px', display:'flex', alignItems:'center', justifyContent:'center' }}>");
lines.push("          <span style={{ fontSize:'clamp(80px,12vw,180px)', fontWeight:900, letterSpacing:'-4px', background:'linear-gradient(180deg,rgba(99,102,241,0.15) 0%, rgba(99,102,241,0.03) 100%)', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', userSelect:'none', whiteSpace:'nowrap' }}>PULSARIQ</span>");
lines.push("        </div>");
lines.push("        <div style={{ borderTop:'1px solid rgba(255,255,255,0.05)', padding:'24px 0', display:'flex', justifyContent:'space-between', alignItems:'center' }}>");
lines.push("          <div style={{ display:'flex', alignItems:'center', gap:'8px' }}>");
lines.push("            <div style={{ width:'24px', height:'24px', borderRadius:'7px', background:'linear-gradient(135deg,#6366F1,#22D3EE)', display:'flex', alignItems:'center', justifyContent:'center' }}><Zap size={12} color=\"#fff\" /></div>");
lines.push("            <span style={{ fontWeight:700, fontSize:'14px' }}>PulsarIQ</span>");
lines.push("          </div>");
lines.push("          <span style={{ fontSize:'12px', color:'#334155' }}>2026 PulsarIQ - Enterprise AI Platform</span>");
lines.push("          <div style={{ display:'flex', gap:'20px' }}>{['Privacy','Terms','Security'].map(t => <span key={t} style={{ fontSize:'12px', color:'#334155', cursor:'pointer' }}>{t}</span>)}</div>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("    </div>");
lines.push("  );");
lines.push("}");

write('app/page.tsx', lines.join('\n'));

console.log('\n  \u2705 Phase 5B complete!\n');
console.log('  Now run: rmdir /s /q .next && npm run dev');
console.log('  Open: http://localhost:3000\n');
