// PulsarIQ — Phase 5D: 3D Holographic Hero + Split Login
// Run: node phase5d.js

const fs   = require('fs');
const path = require('path');
const root = process.cwd();

function write(filePath, content) {
  const full = path.join(root, filePath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content, 'utf8');
  console.log('  \u2713', filePath);
}

console.log('\n  PulsarIQ \u2014 Phase 5D: Holographic Landing\n');

// Add CSS animations to globals.css
const globalsCss = path.join(root, 'app', 'globals.css');
let css = fs.readFileSync(globalsCss, 'utf8');
if (!css.includes('corePulse')) {
  css += `
@keyframes corePulse {
  0%,100% { transform: scale(1); box-shadow: 0 0 40px rgba(99,102,241,0.7), 0 0 80px rgba(99,102,241,0.3); }
  50%      { transform: scale(1.15); box-shadow: 0 0 60px rgba(99,102,241,0.9), 0 0 120px rgba(99,102,241,0.5); }
}
@keyframes orbit1 { from { transform: rotateX(72deg) rotateZ(0deg); }   to { transform: rotateX(72deg) rotateZ(360deg); } }
@keyframes orbit2 { from { transform: rotateX(55deg) rotateZ(180deg); } to { transform: rotateX(55deg) rotateZ(540deg); } }
@keyframes orbit3 { from { transform: rotateX(65deg) rotateZ(90deg); }  to { transform: rotateX(65deg) rotateZ(-270deg); } }
@keyframes orbit4 { from { transform: rotateX(45deg) rotateZ(270deg); } to { transform: rotateX(45deg) rotateZ(-90deg); } }
@keyframes ringRotate { from { transform: rotateX(72deg) rotateZ(0deg); } to { transform: rotateX(72deg) rotateZ(360deg); } }
@keyframes ringRotate2 { from { transform: rotateX(55deg) rotateZ(0deg); } to { transform: rotateX(55deg) rotateZ(-360deg); } }
@keyframes floatY { 0%,100% { transform: translateY(0px); } 50% { transform: translateY(-8px); } }
@keyframes scanLine { 0% { top: 0%; } 100% { top: 100%; } }
@keyframes dataFlow { 0% { opacity:0; transform:translateY(8px); } 50% { opacity:1; } 100% { opacity:0; transform:translateY(-8px); } }
@keyframes glowPulse { 0%,100% { opacity:0.4; } 50% { opacity:1; } }
`;
  fs.writeFileSync(globalsCss, css, 'utf8');
  console.log('  \u2713 globals.css (3D animations)');
}

// Build page as line array (avoids all backtick issues)
const L = [];
const p = (line) => L.push(line);

p("'use client';");
p("import { useEffect, useRef, useState } from 'react';");
p("import { useRouter } from 'next/navigation';");
p("import { createClient } from '@/lib/supabase/client';");
p("import { Zap, ArrowRight } from 'lucide-react';");
p("");
p("export default function LandingPage() {");
p("  const canvasRef = useRef<HTMLCanvasElement>(null);");
p("  const animRef   = useRef<number>(0);");
p("  const frameRef  = useRef(0);");
p("  const [email, setEmail]       = useState('');");
p("  const [password, setPassword] = useState('');");
p("  const [error, setError]       = useState('');");
p("  const [loading, setLoading]   = useState(false);");
p("  const router   = useRouter();");
p("  const supabase = createClient();");
p("");
p("  // Canvas — reactor core + particle streams");
p("  useEffect(() => {");
p("    const canvas = canvasRef.current;");
p("    if (!canvas) return;");
p("    const resize = () => { canvas.width = canvas.offsetWidth; canvas.height = canvas.offsetHeight; };");
p("    resize();");
p("    window.addEventListener('resize', resize);");
p("    const ctx = canvas.getContext('2d');");
p("    if (!ctx) return;");
p("");
p("    // Orbiting particle positions");
p("    const particles: {angle:number; speed:number; radius:number; size:number; color:string}[] = [];");
p("    for (let i = 0; i < 80; i++) {");
p("      particles.push({");
p("        angle:  Math.random() * Math.PI * 2,");
p("        speed:  (Math.random() * 0.008 + 0.003) * (Math.random() > 0.5 ? 1 : -1),");
p("        radius: 80 + Math.random() * 200,");
p("        size:   Math.random() * 1.5 + 0.3,");
p("        color:  Math.random() > 0.5 ? '99,102,241' : '34,211,238',");
p("      });");
p("    }");
p("");
p("    const draw = () => {");
p("      frameRef.current++;");
p("      const W = canvas.width, H = canvas.height;");
p("      const cx = W / 2, cy = H / 2;");
p("      const f = frameRef.current;");
p("      const pulse = (Math.sin(f * 0.04) + 1) / 2;");
p("");
p("      ctx.clearRect(0, 0, W, H);");
p("");
p("      // Background star field");
p("      if (f === 1) {");
p("        (canvas as any)._stars = Array.from({length:120}, () => ({");
p("          x: Math.random() * W, y: Math.random() * H,");
p("          r: Math.random() * 1 + 0.1,");
p("          phase: Math.random() * Math.PI * 2,");
p("        }));");
p("      }");
p("      const stars = (canvas as any)._stars || [];");
p("      stars.forEach((s: any) => {");
p("        s.phase = (s.phase || 0) + 0.008;");
p("        const op = (Math.sin(s.phase) + 1) / 2 * 0.4 + 0.05;");
p("        ctx.beginPath();");
p("        ctx.arc(s.x, s.y, s.r, 0, Math.PI * 2);");
p("        ctx.fillStyle = 'rgba(129,140,248,' + op.toFixed(2) + ')';");
p("        ctx.fill();");
p("      });");
p("");
p("      // Outer ambient glow");
p("      const outerGlow = ctx.createRadialGradient(cx, cy, 0, cx, cy, 300);");
p("      outerGlow.addColorStop(0, 'rgba(99,102,241,' + (0.08 + pulse * 0.05) + ')');");
p("      outerGlow.addColorStop(0.5, 'rgba(99,102,241,0.03)');");
p("      outerGlow.addColorStop(1, 'rgba(99,102,241,0)');");
p("      ctx.beginPath(); ctx.arc(cx, cy, 300, 0, Math.PI * 2);");
p("      ctx.fillStyle = outerGlow; ctx.fill();");
p("");
p("      // Orbit ring guides (dashed)");
p("      [100, 160, 220, 280].forEach((r, i) => {");
p("        ctx.beginPath(); ctx.arc(cx, cy, r, 0, Math.PI * 2);");
p("        ctx.strokeStyle = 'rgba(99,102,241,' + (0.05 - i * 0.008) + ')';");
p("        ctx.lineWidth = 1; ctx.setLineDash([4, 12]); ctx.stroke();");
p("        ctx.setLineDash([]);");
p("      });");
p("");
p("      // Particles on orbits");
p("      particles.forEach(p => {");
p("        p.angle += p.speed;");
p("        const px = cx + Math.cos(p.angle) * p.radius;");
p("        const py = cy + Math.sin(p.angle) * p.radius * 0.35; // flatten for 3D ellipse");
p("        const grd = ctx.createRadialGradient(px, py, 0, px, py, p.size * 3);");
p("        grd.addColorStop(0, 'rgba(' + p.color + ',0.8)');");
p("        grd.addColorStop(1, 'rgba(' + p.color + ',0)');");
p("        ctx.beginPath(); ctx.arc(px, py, p.size * 3, 0, Math.PI * 2);");
p("        ctx.fillStyle = grd; ctx.fill();");
p("        ctx.beginPath(); ctx.arc(px, py, p.size, 0, Math.PI * 2);");
p("        ctx.fillStyle = 'rgba(' + p.color + ',0.9)'; ctx.fill();");
p("      });");
p("");
p("      // Core inner glow layers");
p("      [80, 50, 30].forEach((r, i) => {");
p("        const g = ctx.createRadialGradient(cx, cy, 0, cx, cy, r + pulse * (10 - i * 3));");
p("        const opacity = [0.25, 0.4, 0.7][i] + pulse * 0.15;");
p("        g.addColorStop(0, 'rgba(99,102,241,' + opacity + ')');");
p("        g.addColorStop(0.6, 'rgba(99,102,241,' + (opacity * 0.3) + ')');");
p("        g.addColorStop(1, 'rgba(99,102,241,0)');");
p("        ctx.beginPath(); ctx.arc(cx, cy, r + pulse * (10 - i * 3), 0, Math.PI * 2);");
p("        ctx.fillStyle = g; ctx.fill();");
p("      });");
p("");
p("      // Rotating energy spokes");
p("      for (let i = 0; i < 6; i++) {");
p("        const spokeAngle = (f * 0.01) + (i * Math.PI / 3);");
p("        const x2 = cx + Math.cos(spokeAngle) * (60 + pulse * 10);");
p("        const y2 = cy + Math.sin(spokeAngle) * (60 + pulse * 10);");
p("        const sg = ctx.createLinearGradient(cx, cy, x2, y2);");
p("        sg.addColorStop(0, 'rgba(99,102,241,0.6)');");
p("        sg.addColorStop(1, 'rgba(99,102,241,0)');");
p("        ctx.beginPath(); ctx.moveTo(cx, cy); ctx.lineTo(x2, y2);");
p("        ctx.strokeStyle = sg; ctx.lineWidth = 1; ctx.stroke();");
p("      }");
p("");
p("      animRef.current = requestAnimationFrame(draw);");
p("    };");
p("    draw();");
p("    return () => { cancelAnimationFrame(animRef.current); window.removeEventListener('resize', resize); };");
p("  }, []);");
p("");
p("  const handleLogin = async (e: React.FormEvent) => {");
p("    e.preventDefault();");
p("    setLoading(true); setError('');");
p("    const { error: err } = await supabase.auth.signInWithPassword({ email, password });");
p("    if (err) { setError(err.message); setLoading(false); }");
p("    else router.push('/dashboard');");
p("  };");
p("");
p("  const inp: React.CSSProperties = {");
p("    width: '100%', padding: '11px 14px',");
p("    background: 'rgba(255,255,255,0.05)',");
p("    border: '1px solid rgba(99,102,241,0.25)',");
p("    borderRadius: '10px', color: '#F1F5F9', fontSize: '14px',");
p("    outline: 'none', boxSizing: 'border-box',");
p("    fontFamily: 'Inter,sans-serif',");
p("  };");
p("");
p("  // Holographic panel config");
p("  const panels = [");
p("    { orbit:'orbit1', dur:'12s', radius:220, tilt:-72, color:'#6366F1', title:'Q4 Report.pdf', sub:'847 chunks indexed', stat:'+23% revenue', statColor:'#22C55E' },");
p("    { orbit:'orbit2', dur:'9s',  radius:200, tilt:-55, color:'#22D3EE', title:'AI Query Result', sub:'3,419 queries today', stat:'<200ms response', statColor:'#22D3EE' },");
p("    { orbit:'orbit3', dur:'14s', radius:240, tilt:-65, color:'#A855F7', title:'Knowledge Base', sub:'2,847 documents', stat:'1.2M vector chunks', statColor:'#A855F7' },");
p("    { orbit:'orbit4', dur:'10s', radius:180, tilt:-45, color:'#F59E0B', title:'Access Control', sub:'Admin · 5 members', stat:'RBAC enforced', statColor:'#F59E0B' },");
p("  ];");
p("");
p("  return (");
p("    <div style={{ width:'100%', height:'100vh', overflow:'hidden', background:'#07080F', fontFamily:\"'Inter',sans-serif\", color:'#F1F5F9', position:'relative' }}>");
p("");
p("      {/* Canvas — reactor core */}");
p("      <canvas ref={canvasRef} style={{ position:'absolute', inset:0, width:'100%', height:'100%', zIndex:0 }} />");
p("");
p("      {/* 3D Holographic orbital scene */}");
p("      <div style={{ position:'absolute', inset:0, zIndex:2, perspective:'1000px', display:'flex', alignItems:'center', justifyContent:'center', pointerEvents:'none' }}>");
p("        <div style={{ position:'relative', width:'1px', height:'1px', transformStyle:'preserve-3d' }}>");
p("");
p("          {/* Orbit ring guides (CSS 3D) */}");
p("          {[{a:'ringRotate',d:'20s',rx:72,s:480},{a:'ringRotate2',d:'15s',rx:55,s:420}].map((r,i) => (");
p("            <div key={i} style={{ position:'absolute', width:r.s+'px', height:r.s+'px', marginLeft:-(r.s/2)+'px', marginTop:-(r.s/2)+'px', border:'1px solid rgba(99,102,241,0.08)', borderRadius:'50%', animation:r.a+' '+r.d+' linear infinite', transform:'rotateX('+r.rx+'deg)' }} />");
p("          ))}");
p("");
p("          {/* Reactor core dot */}");
p("          <div style={{ position:'absolute', width:'24px', height:'24px', marginLeft:'-12px', marginTop:'-12px', borderRadius:'50%', background:'linear-gradient(135deg,#fff,#C7D2FE,#6366F1)', animation:'corePulse 2s ease-in-out infinite', boxShadow:'0 0 40px rgba(99,102,241,0.8)' }} />");
p("");
p("          {/* Orbiting data panels */}");
p("          {panels.map((panel, i) => (");
p("            <div key={i} style={{ position:'absolute', animation:panel.orbit+' '+panel.dur+' linear infinite', transformOrigin:'0 0' }}>");
p("              <div style={{ position:'absolute', left:panel.radius+'px', marginTop:'-44px', transform:'rotateX('+panel.tilt+'deg)', animation:'floatY '+(4+i*0.7)+'s ease-in-out infinite' }}>");
p("                <div style={{ width:'160px', padding:'12px 14px', borderRadius:'12px', background:'rgba(13,15,28,0.9)', border:'1px solid '+panel.color+'30', backdropFilter:'blur(20px)', boxShadow:'0 8px 32px rgba(0,0,0,0.4), 0 0 20px '+panel.color+'15', pointerEvents:'none' }}>");
p("                  <div style={{ display:'flex', alignItems:'center', gap:'6px', marginBottom:'8px' }}>");
p("                    <div style={{ width:'6px', height:'6px', borderRadius:'50%', background:panel.color, boxShadow:'0 0 6px '+panel.color, animation:'glowPulse 2s ease-in-out infinite' }} />");
p("                    <span style={{ fontSize:'10px', fontWeight:700, color:panel.color, letterSpacing:'0.5px' }}>{panel.title}</span>");
p("                  </div>");
p("                  <div style={{ fontSize:'11px', color:'#64748B', marginBottom:'6px' }}>{panel.sub}</div>");
p("                  <div style={{ fontSize:'12px', fontWeight:700, color:panel.statColor }}>{panel.stat}</div>");
p("                  {/* Scan line effect */}");
p("                  <div style={{ position:'absolute', left:0, right:0, height:'1px', background:'linear-gradient(90deg,transparent,'+panel.color+'40,transparent)', animation:'scanLine 3s linear infinite', animationDelay:(i*0.8)+'s' }} />");
p("                </div>");
p("              </div>");
p("            </div>");
p("          ))}");
p("        </div>");
p("      </div>");
p("");
p("      {/* Gradient overlay — keeps sides readable */}");
p("      <div style={{ position:'absolute', inset:0, zIndex:3, background:'radial-gradient(ellipse 80% 80% at 50% 50%, transparent 20%, rgba(7,8,15,0.3) 100%)', pointerEvents:'none' }} />");
p("      <div style={{ position:'absolute', left:0, top:0, bottom:0, width:'42%', background:'linear-gradient(to right,rgba(7,8,15,0.92),rgba(7,8,15,0.6),transparent)', zIndex:3, pointerEvents:'none' }} />");
p("      <div style={{ position:'absolute', right:0, top:0, bottom:0, width:'38%', background:'linear-gradient(to left,rgba(7,8,15,0.88),rgba(7,8,15,0.5),transparent)', zIndex:3, pointerEvents:'none' }} />");
p("");
p("      {/* Nav */}");
p("      <nav style={{ position:'absolute', top:0, left:0, right:0, zIndex:20, height:'62px', display:'flex', alignItems:'center', justifyContent:'space-between', padding:'0 44px' }}>");
p("        <div style={{ display:'flex', alignItems:'center', gap:'10px' }}>");
p("          <div style={{ width:'34px', height:'34px', borderRadius:'10px', background:'linear-gradient(135deg,#6366F1,#22D3EE)', display:'flex', alignItems:'center', justifyContent:'center', boxShadow:'0 0 20px rgba(99,102,241,0.5)' }}>");
p("            <Zap size={17} color=\"#fff\" />");
p("          </div>");
p("          <div><div style={{ fontWeight:800, fontSize:'16px', lineHeight:1 }}>PulsarIQ</div><div style={{ fontSize:'9px', color:'#64748B', letterSpacing:'1.2px' }}>ENTERPRISE AI</div></div>");
p("        </div>");
p("        <div style={{ display:'flex', gap:'28px', fontSize:'13px' }}>");
p("          <a href=\"#\" style={{ color:'#64748B', textDecoration:'none' }}>Features</a>");
p("          <a href=\"#\" style={{ color:'#64748B', textDecoration:'none' }}>How it works</a>");
p("          <a href=\"/signup\" style={{ color:'#22D3EE', textDecoration:'none', fontWeight:600 }}>Create workspace</a>");
p("        </div>");
p("      </nav>");
p("");
p("      {/* LEFT: Headline */}");
p("      <div style={{ position:'absolute', left:0, top:0, bottom:0, zIndex:10, display:'flex', flexDirection:'column', justifyContent:'center', padding:'0 0 0 48px', maxWidth:'42%' }}>");
p("        <h1 style={{ fontSize:'clamp(42px,4.5vw,68px)', fontWeight:900, lineHeight:1.04, margin:'0 0 18px', letterSpacing:'-2.5px' }}>");
p("          Your knowledge,");
p("          <br />");
p("          <span style={{ background:'linear-gradient(90deg,#6366F1,#22D3EE)', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', display:'block' }}>pulsing with");
p("            intelligence.");
p("          </span>");
p("        </h1>");
p("        <p style={{ fontSize:'16px', color:'#64748B', lineHeight:1.7, margin:'0 0 28px', maxWidth:'360px' }}>");
p("          Upload any document. Ask any question. Get precise answers with exact citations — instantly.");
p("        </p>");
p("        <div style={{ display:'flex', flexDirection:'column', gap:'8px' }}>");
p("          {[");
p("            { dot:'#6366F1', text:'Self-hosted — your data never leaves' },");
p("            { dot:'#22D3EE', text:'Vector search across millions of chunks' },");
p("            { dot:'#A855F7', text:'Enterprise RBAC with multi-tenancy' },");
p("          ].map(({dot,text}) => (");
p("            <div key={text} style={{ display:'flex', alignItems:'center', gap:'10px' }}>");
p("              <div style={{ width:'5px', height:'5px', borderRadius:'50%', background:dot, flexShrink:0 }} />");
p("              <span style={{ fontSize:'13px', color:'#475569' }}>{text}</span>");
p("            </div>");
p("          ))}");
p("        </div>");
p("      </div>");
p("");
p("      {/* RIGHT: Login form */}");
p("      <div style={{ position:'absolute', right:48, top:0, bottom:0, zIndex:10, display:'flex', flexDirection:'column', justifyContent:'center', width:'340px' }}>");
p("        <div style={{ padding:'32px', borderRadius:'18px', background:'rgba(13,15,28,0.92)', border:'1px solid rgba(99,102,241,0.2)', backdropFilter:'blur(40px)', boxShadow:'0 32px 80px rgba(0,0,0,0.6)' }}>");
p("          <div style={{ marginBottom:'24px' }}>");
p("            <h2 style={{ fontSize:'20px', fontWeight:800, margin:'0 0 4px', letterSpacing:'-0.5px' }}>Sign in to PulsarIQ</h2>");
p("            <p style={{ fontSize:'13px', color:'#64748B', margin:0 }}>Access your enterprise knowledge base</p>");
p("          </div>");
p("          <form onSubmit={handleLogin} style={{ display:'flex', flexDirection:'column', gap:'14px' }}>");
p("            <div>");
p("              <label style={{ fontSize:'12px', color:'#64748B', display:'block', marginBottom:'6px', fontWeight:500 }}>Work Email</label>");
p("              <input type=\"email\" required value={email} onChange={e => setEmail(e.target.value)} placeholder=\"you@company.com\" style={inp} />");
p("            </div>");
p("            <div>");
p("              <label style={{ fontSize:'12px', color:'#64748B', display:'block', marginBottom:'6px', fontWeight:500 }}>Password</label>");
p("              <input type=\"password\" required value={password} onChange={e => setPassword(e.target.value)} placeholder=\"••••••••\" style={inp} />");
p("            </div>");
p("            {error && <div style={{ fontSize:'12px', color:'#EF4444', padding:'8px 12px', background:'rgba(239,68,68,0.08)', borderRadius:'8px', border:'1px solid rgba(239,68,68,0.2)' }}>{error}</div>}");
p("            <button type=\"submit\" disabled={loading} style={{ padding:'13px', borderRadius:'11px', background:'linear-gradient(135deg,#6366F1,#22D3EE)', border:'none', color:'#fff', fontSize:'14px', fontWeight:700, cursor:loading ? 'wait':'pointer', opacity:loading ? 0.7:1, boxShadow:'0 4px 24px rgba(99,102,241,0.45)', display:'flex', alignItems:'center', justifyContent:'center', gap:'8px', marginTop:'4px' }}>");
p("              {loading ? 'Signing in...' : 'Sign In'} {!loading && <ArrowRight size={15} />}");
p("            </button>");
p("          </form>");
p("          <div style={{ marginTop:'18px', paddingTop:'18px', borderTop:'1px solid rgba(255,255,255,0.05)', textAlign:'center' }}>");
p("            <p style={{ fontSize:'13px', color:'#64748B', margin:'0 0 10px' }}>New to PulsarIQ?</p>");
p("            <a href=\"/signup\" style={{ display:'inline-flex', alignItems:'center', gap:'6px', padding:'9px 20px', borderRadius:'9px', border:'1px solid rgba(99,102,241,0.3)', color:'#6366F1', fontSize:'13px', fontWeight:600, textDecoration:'none', background:'rgba(99,102,241,0.06)' }}>Create your workspace <ArrowRight size={13} /></a>");
p("          </div>");
p("        </div>");
p("        <p style={{ textAlign:'center', fontSize:'11px', color:'#334155', marginTop:'12px' }}>SOC2 Ready &#183; On-Premise AI &#183; Zero Data Exposure</p>");
p("      </div>");
p("");
p("      {/* PULSARIQ cosmic footer text */}");
p("      <div style={{ position:'absolute', bottom:0, left:0, right:0, zIndex:1, overflow:'hidden', height:'100px', display:'flex', alignItems:'flex-end', justifyContent:'center', pointerEvents:'none' }}>");
p("        <span style={{ fontSize:'clamp(70px,10vw,140px)', fontWeight:900, letterSpacing:'-4px', background:'linear-gradient(180deg,rgba(99,102,241,0.1) 0%,rgba(99,102,241,0.02) 100%)', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', userSelect:'none', whiteSpace:'nowrap', lineHeight:1 }}>PULSARIQ</span>");
p("      </div>");
p("    </div>");
p("  );");
p("}");

write('app/page.tsx', L.join('\n'));

console.log('\n  \u2705 Phase 5D complete!\n');
console.log('  Run: rmdir /s /q .next && npm run dev');
console.log('  Open: http://localhost:3000\n');
